#
# Configure github
#
github:

  # Main features
  features:
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: true

  # Buttons
  enabled_merge_buttons:
    # Disable squash button:
    squash: false
    # enable merge button:
    merge: true
    # disable rebase button:
    rebase: false

  # Close branches when pull requests are merged
  del_branch_on_merge: true

  labels:
    - website
    - pelican

#
# Configure Pelican
#
# See also:
# * https://infra.apache.org/project-site.html
# * https://infra.apache.org/asf-pelican-gettingstarted.html
#
pelican:
  notify: commits@buildstream.apache.org
  autobuild: preview/*
  target: asf-site
  theme: theme/apache
  whoami: main

#
# Staging website
#
staging:
  profile: ~
  whoami: staging
  autostage: preview/*
