image: python:3.7-alpine

before_script:
- apk add --update make
- pip3 install -r requirements.txt

test:
  script:
  - make html
  - make serve &
  - sleep 0.2
  - pylinkvalidate.py -P 127.0.0.1:8000
  artifacts:
    paths:
    - output/
  except:
  - master

pages:
  script:
  - make publish
  - mv output public
  artifacts:
    paths:
    - public/
  only:
  - master
